# Generated by Django 4.2 on 2026-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the task', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Due date for the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when task was last updated')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='tasks_task_status_a96e51_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', '-created_at'], name='tasks_task_priorit_87e91a_idx'),
        ),
    ]
